<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c045a522-bd8e-46b8-b0ad-dcb8a2c695b7</UserSecretsId>
	  <!-- ⚡ Фикс для работы Microsoft.Data.SqlClient при сборке в SingleFile -->
	  <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="54.2.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.11" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
