// <auto-generated />
using System;
using BackupServer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackupServer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BackupServer.Core.Entities.BackupLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FileCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PointId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("BackupLogs");
                });

            modelBuilder.Entity("BackupServer.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BackupServer.Core.Entities.ExchangeOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("ExchangeOffices");
                });

            modelBuilder.Entity("BackupServer.Core.Entities.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExchangeOfficeId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ExpectedDeadline")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("ExchangeOfficeId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("BackupServer.Core.Entities.BackupLog", b =>
                {
                    b.HasOne("BackupServer.Core.Entities.Point", "Point")
                        .WithMany("BackupLogs")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");
                });

            modelBuilder.Entity("BackupServer.Core.Entities.ExchangeOffice", b =>
                {
                    b.HasOne("BackupServer.Core.Entities.City", "City")
                        .WithMany("ExchangeOffices")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("BackupServer.Core.Entities.Point", b =>
                {
                    b.HasOne("BackupServer.Core.Entities.ExchangeOffice", "ExchangeOffice")
                        .WithMany("Points")
                        .HasForeignKey("ExchangeOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeOffice");
                });

            modelBuilder.Entity("BackupServer.Core.Entities.City", b =>
                {
                    b.Navigation("ExchangeOffices");
                });

            modelBuilder.Entity("BackupServer.Core.Entities.ExchangeOffice", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("BackupServer.Core.Entities.Point", b =>
                {
                    b.Navigation("BackupLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
